### ISSUE TITLE
Cannot retrieve exit code for ad-hoc command run via s6 init

### ISSUE THREAD

**Issue by agaffney** [just-containers/s6-overlay#73]
I have images that use the s6-overlay /init as the ENTRYPOINT. The init scripts allow running an ad-hoc command that will be supervised by s6 along with the other configured services, but there doesn't seem to be a way to retrieve the exit code of that ad-hoc command (understandably).

However, it seems that it should be possible to capture the exit code of that ad-hoc command (and perhaps write it to a file) and then exit with that code in the shutdown scripts. I'm assuming this without having dug around too much in the overlay code or being all that familiar with S6 in general.

I can work around this by bypassing S6 at runtime with --entrypoint=/bin/bash and then prepending my command with "-c", but this is a bit ugly.

**Comment by agaffney** [comment]
Looking at the overly code, it appears that init-stage2 actually is capturing the exit code, but it doesn't look like it's being used in init-stage3.

You can see the difference here:

```
$ sudo docker run --entrypoint="/bin/bash" -ti --rm tops-base/build -c "exit 1"; echo $?
1
```

vs.

```
$ sudo docker run -ti --rm tops-base/build bash -c "exit 1"; echo $?
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
bash exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
0
```

**Comment by glerchundi** [comment]
CMD command exit code is saved in `/var/run/env-stage3/S6_CMD_EXITED` and it's made available in all s6 finish scripts, even in the main s6 finish one (`/etc/s6/services/.s6-svscan/finish` which is hier-copyied in runtime to `/var/run/s6/services/.s6-svscan/finish`). So you can just do this:

```
docker run -ti -e S6_KILL_GRACETIME=0 -v `pwd`/asdf:/var/run/s6/env-stage3 quay.io/justcontainers/base-alpine:v0.8.0 exit 2
cat ./asdf/S6_CMD_EXITED
```

But it would be great to go out with the exit code of the command if this was present, i'll try it out and see if it makes sense.

**Comment by skarnet** [comment]
At the end of `/etc/s6/init/init-stage3` in the overlay, replace `s6-sync` with:
```
foreground { s6-sync }
import -u -D0 S6_CMD_EXITED
exit $S6_CMD_EXITED
```
That should do what you want.

**Comment by glerchundi** [comment]
it worked! :-)

Previously I did exactly that but without foregrounding s6-sync, I thought (prematurely) it was a chainable one.

I'm going to push a new version with this.

**Comment by glerchundi** [comment]
#74 should fix this. I've already released a new version v1.14.0.1 which includes this change.

```
$> docker run quay.io/justcontainers/base-alpine:v0.8.1 sh -c 'exit 111'
$> echo $?
111
```

**Comment by cmfatih** [comment]
@glerchundi : this might be still broken...

I have the following `finish` script

```
#!/usr/bin/with-contenv sh

echo "[app/finish] finishing ($0 $1 $?)"
s6-svscanctl -t /var/run/s6/services
```

and here is output once my app exits > 0

```
[app/finish] finishing (./finish 111 0)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
Received HUP, reloading configuration...
[s6-finish] sending all processes the KILL signal and exiting.
/tmp$ echo $?
0
```

I can see that finish script receives the exit code `(./finish 111 0)` but it doesn't pass to host. How can I pass that exit code into host machine?

P.S.: I'm using `1.17.1.1`

**Comment by skarnet** [comment]
The current overlay will only return the exit code of a CMD.
Here, it looks like you have no CMD, but you want to return the exit code of a supervised service instead.

There are ways to hack around this, but if you're going to bring the container down as soon as your service exits, why are you supervising it? Unless you want to take advantage of supervision (sending signals to your daemon, auto-restarts etc.) you're better off simply running it as a CMD instead, and your host will get the correct exit code.

**Comment by cmfatih** [comment]
@skarnet : thanks for your reply...

I have multi pid container, that's the reason I'm using s6. Basically I have multiple services (under `/etc/services.d/`) and one of it is a web service. I would like to propagate web service's exit code to host (it has finish script). 

And yes I don't have `CMD`, I have `ENTRYPOINT`;

```
ENTRYPOINT ["/init"]
CMD []
```

is there a solution for my issue?

**Comment by skarnet** [comment]
Again, since you're not really using the supervision features for your web service (you tear down the container as soon as it exits), I suggest you to take it out of `/etc/services.d/` and run it as a CMD instead. It's the simplest way of achieving what you want. Generally, if you run a program once and kill the machine when it dies, that program is not a good candidate for supervision.

There are other solutions (for instance, have your `./finish` script write the exit code to the appropriate place in the filesystem, so that stage 3 will read it), but they will definitely be more hackish than just isolating the one service your whole container is depending on and not supervising it.

**Comment by cmfatih** [comment]
@skarnet : Thanks, I got your point but I have multi pid container. I have to use supervision for running other stuff along with my web service in the container. Seems like I have two options;

1. Use CMD: point a shell script that runs `/init` (as background process) then do something like `exec my-app` which will replace the process. (I haven't tried it yet)

2. Use `finish` script. You said `write the exit code to the appropriate place in the filesystem, so that stage 3 will read it` do you have an example?

I would like to try both

**Comment by glerchundi** [comment]
@cmfatih what @skarnet says is to take just you main service out from `/etc/services.d` and keep the rest there so that if your main process exits its exit code will be captured by docker. You can create a multi pid container using CMD as well.

**Comment by cmfatih** [comment]
Ahh, I see... Thanks
